### ISSUE TITLE
Google Analytics not rendering inside head or body

### ISSUE THREAD

**Issue by digitalLeaderAuthor** [noBugsException/MBN-shop#13]
![image](https://cloud.githubusercontent.com/assets/19479619/24587996/b7a4aa9e-17c8-11e7-83ae-b135caabe00f.png)

**Comment by AValintsev** [comment]
Нужно галочку "активно" установить

![image](https://cloud.githubusercontent.com/assets/20658660/24590126/57055c74-17f0-11e7-8357-1cf5797e93ac.png)
