### ISSUE TITLE
Money selector not working as expected

### ISSUE THREAD

**Issue by digitalLeaderAuthor** [noBugsException/MBN-shop#2]
![image](https://cloud.githubusercontent.com/assets/19479619/24410141/f3873dfc-13da-11e7-8967-715948de2dc7.png)

**Comment by AValintsev** [comment]
Нужно поменять Отображение для языка
![image](https://cloud.githubusercontent.com/assets/20658660/24424819/aa1ed19a-140a-11e7-81ce-eb2569ff4b65.png)

**Comment by AValintsev** [comment]
И еще нужно сделать новый плагин. Для конвертации валют в гривну автоматически
